name:                Risk-Game
version:             0.1.0.0
github:              "aaksn/Functional-Programming"
license:             BSD3
author:              "Aksenov Anton"
maintainer:          "example@example.com"
copyright:           "2021 Aksenov Anton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Risk-Game#readme>

dependencies:
- base >= 4.7 && < 5
- MonadRandom
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  Risk-Game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Risk-Game

tests:
  Risk-Game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Risk-Game
